application_mode_inputs: list[tuple[str, int]] = [
    ('1st phase - general contingent', 1),
    ('Ordinance No. 612/93', 2),
    ('1st phase - special contingent (Azores Island)', 5),
    ('Holders of other higher courses', 7),
    ('Ordinance No. 854-B/99', 10),
    ('International student (bachelor)', 15),
    ('1st phase - special contingent (Madeira Island)', 16),
    ('2nd phase - general contingent', 17),
    ('3rd phase - general contingent', 18),
    ('Ordinance No. 533-A/99, item b2) (Different Plan)', 26),
    ('Ordinance No. 533-A/99, item b3 (Other Institution)', 27),
    ('Over 23 years old', 39),
    ('Transfer', 42),
    ('Change of course', 43),
    ('Technological specialization diploma holders', 44),
    ('Change of institution/course', 51),
    ('Short cycle diploma holders', 53),
    ('Change of institution/course (International)', 57),
]
