course_inputs: list[tuple[str, int]] = [
    ('Biofuel Production Technologies', 33),
    ('Animation and Multimedia Design', 171),
    ('Social Service (evening attendance)', 8014),
    ('Agronomy', 9003),
    ('Communication Design', 9070),
    ('Veterinary Nursing', 9085),
    ('Informatics Engineering', 9119),
    ('Equinculture', 9130),
    ('Management', 9147),
    ('Social Service', 9238),
    ('Tourism', 9254),
    ('Nursing', 9500),
    ('Oral Hygiene', 9556),
    ('Advertising and Marketing Management', 9670),
    ('Journalism and Communication', 9773),
    ('Basic Education', 9853),
    ('Management (evening attendance)', 9991),
]
