fathers_occupation_inputs: list[tuple[str, int]] = [
    ('Student', 0),
    ('Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers',
     1),
    ('Specialists in Intellectual and Scientific Activities', 2),
    ('Intermediate Level Technicians and Professions', 3),
    ('Administrative staff', 4),
    ('Personal Services, Security and Safety Workers and Sellers', 5),
    ('Farmers and Skilled Workers in Agriculture, Fisheries and Forestry', 6),
    ('Skilled Workers in Industry, Construction and Craftsmen', 7),
    ('Installation and Machine Operators and Assembly Workers', 8),
    ('Unskilled Workers', 9),
    ('Armed Forces Professions', 10),
    ('Other Situation', 90),
    ('(blank)', 99),
    ('Armed Forces Officers', 101),
    ('Armed Forces Sergeants', 102),
    ('Other Armed Forces personnel', 103),
    ('Directors of administrative and commercial services', 112),
    ('Hotel, catering, trade and other services directors', 114),
    # ('Specialists in the physical sciences, mathematics, engineering and related techniques', 121),
    ('Health professionals', 122),
    ('teachers', 123),
    ('Specialists in finance, accounting, administrative organization, public and commercial relations',
     124),
    ('Intermediate level science and engineering technicians and professions',
     131),
    # ('Technicians and professionals, of intermediate level of health', 132),
    # ('Intermediate level technicians from legal, social, sports, cultural and similar services', 134),
    ('Information and communication technology technicians', 135),
    ('Office workers, secretaries in general and data processing operators',
     141),
    ('Data, accounting, statistical, financial services and registry-related operators',
     143),
    ('Other administrative support staff', 144),
    ('Personal service workers', 151),
    ('Sellers', 152),
    ('Personal care workers and the like', 153),
    ('Protection and security services personnel', 154),
    # ('Market-oriented farmers and skilled agricultural and animal production workers', 161),
    ('Farmers, livestock keepers, fishermen, hunters and gatherers, subsistence',
     163),
    ('Skilled construction workers and the like, except electricians', 171),
    ('Skilled workers in metallurgy, metalworking and similar', 172),
    ('Skilled workers in electricity and electronics', 174),
    ('Workers in food processing, woodworking, clothing and other industries and crafts',
     175),
    ('Fixed plant and machine operators', 181),
    ('Assembly workers', 182),
    ('Vehicle drivers and mobile equipment operators', 183),
    ('Unskilled workers in agriculture, animal production, fisheries and forestry',
     192),
    ('Unskilled workers in extractive industry, construction, manufacturing and transport',
     193),
    ('Meal preparation assistants', 194),
    ('Street vendors (except food) and street service providers', 195),
]
