fathers_qualification_inputs: list[tuple[str, int]] = [
    ('Secondary Education - 12th Year of Schooling or Eq.', 1),
    ('Higher Education - Bachelor\'s Degree', 2),
    ('Higher Education - Degree', 3),
    ('Higher Education - Master\'s', 4),
    ('Higher Education - Doctorate', 5),
    ('Frequency of Higher Education', 6),
    ('12th Year of Schooling - Not Completed', 9),
    ('11th Year of Schooling - Not Completed', 10),
    ('7th Year (Old)', 11),
    ('Other - 11th Year of Schooling', 12),
    ('2nd year complementary high school course', 13),
    ('10th Year of Schooling', 14),
    ('General commerce course', 18),
    ('Basic Education 3rd Cycle (9th/10th/11th Year) or Equiv.', 19),
    ('Complementary High School Course', 20),
    ('Technical-professional course', 22),
    ('Complementary High School Course - not concluded', 25),
    ('7th year of schooling', 26),
    ('2nd cycle of the general high school course', 27),
    ('9th Year of Schooling - Not Completed', 29),
    ('8th year of schooling', 30),
    ('General Course of Administration and Commerce', 31),
    ('Supplementary Accounting and Administration', 33),
    ('Unknown', 34),
    ('Can\'t read or write', 35),
    ('Can read without having a 4th year of schooling', 36),
    ('Basic education 1st cycle (4th/5th year) or equiv.', 37),
    ('Basic Education 2nd Cycle (6th/7th/8th Year) or Equiv.', 38),
    ('Technological specialization course', 39),
    ('Higher education - degree (1st cycle)', 40),
    ('Specialized higher studies course', 41),
    ('Professional higher technical course', 42),
    ('Higher Education - Master (2nd cycle)', 43),
    ('Higher Education - Doctorate (3rd cycle)', 44),
]
