# FIXME: Find a way to be able to uncomment commented fields due to input

mothers_occupation_inputs: list[tuple[str, int]] = [
    ('Student', 0),
    ('Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers',
     1),
    ('Specialists in Intellectual and Scientific Activities', 2),
    ('Intermediate Level Technicians and Professions', 3),
    ('Administrative staff', 4),
    ('Personal Services, Security and Safety Workers and Sellers', 5),
    ('Farmers and Skilled Workers in Agriculture, Fisheries and Forestry', 6),
    ('Skilled Workers in Industry, Construction and Craftsmen', 7),
    ('Installation and Machine Operators and Assembly Workers', 8),
    ('Unskilled Workers', 9),
    ('Armed Forces Professions', 10),
    ('Other Situation', 90),
    ('(blank)', 99),
    # ('Health professionals', 122),
    ('teachers', 123),
    ('Specialists in information and communication technologies (ICT)', 125),
    # ('Intermediate level science and engineering technicians and professions', 131),
    ('Technicians and professionals, of intermediate level of health', 132),
    ('Intermediate level technicians from legal, social, sports, cultural and similar services',
     134),
    ('Office workers, secretaries in general and data processing operators',
     141),
    ('Data, accounting, statistical, financial services and registry-related operators',
     143),
    ('Other administrative support staff', 144),
    ('personal service workers', 151),
    ('sellers', 152),
    ('Personal care workers and the like', 153),
    ('Skilled construction workers and the like, except electricians', 171),
    # ('Skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like',
    #  173),
    ('Workers in food processing, woodworking, clothing and other industries and crafts',
     175),
    ('cleaning workers', 191),
    ('Unskilled workers in agriculture, animal production, fisheries and forestry',
     192),
    ('Unskilled workers in extractive industry, construction, manufacturing and transport',
     193),
    ('Meal preparation assistants', 194),
]
