previous_qualification_inputs: list[tuple[str, int]] = [
    ('Secondary education', 1),
    ('Higher education - bachelor\'s degree', 2),
    ('Higher education - degree', 3),
    ('Higher education - master\'s', 4),
    ('Higher education - doctorate', 5),
    ('Frequency of higher education', 6),
    ('12th year of schooling - not completed', 9),
    ('11th year of schooling - not completed', 10),
    ('Other - 11th year of schooling', 12),
    ('10th year of schooling', 14),
    ('10th year of schooling - not completed', 15),
    ('Basic education 3rd cycle (9th/10th/11th year) or equiv.', 19),
    ('Basic education 2nd cycle (6th/7th/8th year) or equiv.', 38),
    ('Technological specialization course', 39),
    ('Higher education - degree (1st cycle)', 40),
    ('Professional higher technical course', 42),
    ('Higher education - master (2nd cycle)', 43),
]
